import type { Product } from "@/types";

const now = new Date("2026-01-01T00:00:00.000Z");

export const FALLBACK_PRODUCTS: Product[] = [
  {
    id: "fallback-sobal-launch",
    title: "Sobal Launch",
    slug: "sobal-launch",
    description: "A production-ready SaaS starter kit with authentication, billing, team workspaces, admin dashboard, and deployment pipelines — everything you need to ship your SaaS in days instead of months.",
    content: `<h2>What is Sobal Launch?</h2><p>Sobal Launch is SobalTech's flagship SaaS accelerator. It gives you a fully integrated, production-ready codebase so you can focus on your product rather than rebuilding infrastructure every time.</p><h2>What is included?</h2><ul><li>Next.js 15 App Router with TypeScript</li><li>Authentication with NextAuth (email, Google, GitHub)</li><li>Stripe billing with subscription plans and usage-based options</li><li>Multi-tenant team workspaces with role-based permissions</li><li>Admin dashboard for user and subscription management</li><li>Transactional emails via Resend</li><li>PostgreSQL + Prisma ORM with migrations</li><li>CI/CD pipelines and one-click Vercel deployment</li><li>Dark mode, mobile-responsive UI built on Tailwind and shadcn/ui</li></ul><h2>Who is it for?</h2><p>Founders and teams who need to launch a B2B or B2C SaaS product quickly without spending months on boilerplate. We customize it to your brand and product requirements before handover.</p>`,
    icon: "LayoutDashboard",
    image: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=1200&h=600&auto=format&fit=crop&q=80",
    features: [
      "Auth (email, Google, GitHub)",
      "Stripe billing and subscriptions",
      "Multi-tenant workspaces",
      "Admin dashboard",
      "Transactional emails",
      "CI/CD and Vercel deployment",
    ],
    price: "From ₵15,000",
    ctaLabel: "Request Demo",
    ctaHref: "/request-quote",
    order: 0,
    isPublished: true,
    seoTitle: "Sobal Launch — SaaS Starter Kit | SobalTech",
    seoDesc: "Production-ready SaaS starter with auth, Stripe billing, team workspaces, and admin dashboard. Ship your SaaS in days.",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "fallback-sobal-shop",
    title: "Sobal Shop",
    slug: "sobal-shop",
    description: "A fully featured e-commerce platform with product management, cart, checkout, payments, order tracking, and a merchant dashboard — built to scale from your first sale to thousands of orders.",
    content: `<h2>What is Sobal Shop?</h2><p>Sobal Shop is a custom e-commerce platform built for merchants who need more control than Shopify offers, without the cost of building from scratch. We configure and customize it for your inventory, brand, and checkout flow.</p><h2>What is included?</h2><ul><li>Product catalogue with variants, categories, and inventory tracking</li><li>Shopping cart and wishlist with offline persistence</li><li>Stripe and mobile money payment integration</li><li>Order management with status tracking and email notifications</li><li>Merchant dashboard for products, orders, and analytics</li><li>Customer accounts and order history</li><li>SEO-optimised product pages and sitemaps</li><li>Mobile-first responsive design</li></ul><h2>Who is it for?</h2><p>Retailers, fashion brands, electronics merchants, and any business selling physical or digital products who want a custom storefront they fully own.</p>`,
    icon: "ShoppingCart",
    image: "https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=1200&h=600&auto=format&fit=crop&q=80",
    features: [
      "Product catalogue and inventory",
      "Cart, checkout, and payments",
      "Order tracking and notifications",
      "Merchant dashboard",
      "Customer accounts",
      "Mobile-first design",
    ],
    price: "From ₵12,000",
    ctaLabel: "Request Demo",
    ctaHref: "/request-quote",
    order: 1,
    isPublished: true,
    seoTitle: "Sobal Shop — E-Commerce Platform | SobalTech",
    seoDesc: "Custom e-commerce platform with product management, Stripe payments, order tracking, and merchant dashboard.",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "fallback-sobal-analytics",
    title: "Sobal Analytics",
    slug: "sobal-analytics",
    description: "A real-time business analytics dashboard with customisable KPI tracking, automated reports, data source integrations, and AI-powered insights — built for teams who make decisions from data.",
    content: `<h2>What is Sobal Analytics?</h2><p>Sobal Analytics is a customisable business intelligence platform that connects your data sources and turns raw numbers into clear, actionable dashboards your whole team can use — without needing a data engineer on call.</p><h2>What is included?</h2><ul><li>Drag-and-drop dashboard builder with 10+ chart types</li><li>Connectors for popular data sources (Stripe, Google Analytics, PostgreSQL, APIs)</li><li>Real-time data refresh with configurable intervals</li><li>Scheduled email reports for stakeholders</li><li>AI-powered anomaly detection and plain-English summaries</li><li>Role-based access for analysts, managers, and executives</li><li>CSV and PDF export for all reports</li></ul><h2>Who is it for?</h2><p>Operations teams, growth teams, and executives who need a single place to monitor business health without switching between 5 different tools.</p>`,
    icon: "BarChart3",
    image: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=1200&h=600&auto=format&fit=crop&q=80",
    features: [
      "Drag-and-drop dashboard builder",
      "Multi-source data connectors",
      "AI anomaly detection",
      "Scheduled reports",
      "Role-based access",
      "CSV and PDF export",
    ],
    price: "From ₵18,000",
    ctaLabel: "Request Demo",
    ctaHref: "/request-quote",
    order: 2,
    isPublished: true,
    seoTitle: "Sobal Analytics — Business Intelligence Platform | SobalTech",
    seoDesc: "Real-time analytics dashboard with KPI tracking, AI insights, and automated reports for data-driven teams.",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "fallback-sobal-admin",
    title: "Sobal Admin",
    slug: "sobal-admin",
    description: "A powerful, customisable admin portal for managing users, content, operations, and data — with granular role permissions, audit logs, and a clean interface your team will actually enjoy using.",
    content: `<h2>What is Sobal Admin?</h2><p>Sobal Admin is a fully customisable internal operations dashboard. Whether you need to manage users, approve content, monitor orders, or configure your platform settings, we build it around your exact workflows.</p><h2>What is included?</h2><ul><li>User and role management with granular permissions</li><li>Content management interface (articles, products, listings)</li><li>Data tables with search, filter, sort, and bulk actions</li><li>Audit log for all admin actions</li><li>Configurable widgets and dashboard panels</li><li>Two-factor authentication for admin accounts</li><li>Activity monitoring and session management</li></ul><h2>Who is it for?</h2><p>Operations teams, content managers, and platform administrators who need a purpose-built internal tool instead of a generic CMS or a spreadsheet.</p>`,
    icon: "Package",
    image: "https://images.unsplash.com/photo-1542744094-3a31f272c490?w=1200&h=600&auto=format&fit=crop&q=80",
    features: [
      "User and role management",
      "Content management interface",
      "Audit logs",
      "Granular permissions",
      "Two-factor authentication",
      "Configurable dashboards",
    ],
    price: "From ₵10,000",
    ctaLabel: "Request Demo",
    ctaHref: "/request-quote",
    order: 3,
    isPublished: true,
    seoTitle: "Sobal Admin — Internal Operations Portal | SobalTech",
    seoDesc: "Customisable admin portal with user management, audit logs, role permissions, and content management.",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "fallback-sobal-mobile",
    title: "Sobal Mobile",
    slug: "sobal-mobile",
    description: "A cross-platform mobile app starter for iOS and Android built with React Native — with authentication, push notifications, offline support, and app store submission handled for you.",
    content: `<h2>What is Sobal Mobile?</h2><p>Sobal Mobile is SobalTech's React Native accelerator for teams that need a polished mobile app on both iOS and Android without maintaining two separate codebases. We customise it to your product and handle the entire App Store and Google Play submission process.</p><h2>What is included?</h2><ul><li>React Native and Expo codebase for iOS and Android</li><li>Authentication (email, social login, biometric unlock)</li><li>Push notification system with segmentation and scheduling</li><li>Offline-first data persistence with sync on reconnect</li><li>Navigation with deep linking support</li><li>In-app purchases and subscription management</li><li>App Store and Google Play submission</li><li>Over-the-air update support via Expo Updates</li></ul><h2>Who is it for?</h2><p>Startups and businesses that need a native-quality mobile app on both platforms without the cost of two separate native engineering teams.</p>`,
    icon: "Layers",
    image: "https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=1200&h=600&auto=format&fit=crop&q=80",
    features: [
      "iOS and Android from one codebase",
      "Auth and biometric unlock",
      "Push notifications",
      "Offline-first support",
      "In-app purchases",
      "App store submission",
    ],
    price: "From ₵20,000",
    ctaLabel: "Request Demo",
    ctaHref: "/request-quote",
    order: 4,
    isPublished: true,
    seoTitle: "Sobal Mobile — React Native App Starter | SobalTech",
    seoDesc: "Cross-platform React Native mobile app with auth, push notifications, offline support, and app store submission.",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "fallback-sobal-ai",
    title: "Sobal AI",
    slug: "sobal-ai",
    description: "An AI integration framework that adds intelligent features to your existing product — chatbots, document processing, natural language search, content generation, and custom model fine-tuning.",
    content: `<h2>What is Sobal AI?</h2><p>Sobal AI is a modular AI integration layer we plug into your existing product or build into a new one. Rather than building generic AI features, we design integrations that solve specific problems in your workflow and deliver measurable outcomes.</p><h2>What is included?</h2><ul><li>AI chatbot with custom knowledge base (RAG architecture)</li><li>Document processing and extraction (PDFs, invoices, forms)</li><li>Natural language search across your data</li><li>AI content generation tuned to your brand voice</li><li>Automated data classification and tagging</li><li>Custom model fine-tuning for domain-specific tasks</li><li>Usage monitoring, cost controls, and caching layer</li></ul><h2>Who is it for?</h2><p>Businesses that want to add AI capabilities to their product or internal workflows without hiring an ML team or building LLM infrastructure from scratch.</p>`,
    icon: "Bot",
    image: "https://images.unsplash.com/photo-1677442135703-1787eea5ce01?w=1200&h=600&auto=format&fit=crop&q=80",
    features: [
      "Custom AI chatbot with RAG",
      "Document processing and extraction",
      "Natural language search",
      "AI content generation",
      "Custom model fine-tuning",
      "Usage monitoring and cost controls",
    ],
    price: "From ₵25,000",
    ctaLabel: "Request Demo",
    ctaHref: "/request-quote",
    order: 5,
    isPublished: true,
    seoTitle: "Sobal AI — AI Integration Framework | SobalTech",
    seoDesc: "Add AI to your product: chatbots, document processing, natural language search, and custom model fine-tuning.",
    createdAt: now,
    updatedAt: now,
  },
];

export function getFallbackProduct(slug: string) {
  return FALLBACK_PRODUCTS.find((p) => p.slug === slug) ?? null;
}
